### ISSUE TITLE
It's-a-me

### ISSUE THREAD

**Issue by aleasto** [QUB3X/Appunti#1]
-1 -> -i
https://github.com/QUB3X/Appunti/blob/6b4a7ee39cc99a015f36ec93ff03fc593ba68e95/API/Algoritmi.tex#L195

log_2 -> log
https://github.com/QUB3X/Appunti/blob/6b4a7ee39cc99a015f36ec93ff03fc593ba68e95/API/Algoritmi.tex#L216

di lunghezza che?
https://github.com/QUB3X/Appunti/blob/6b4a7ee39cc99a015f36ec93ff03fc593ba68e95/API/Algoritmi.tex#L401

+1 -> +i
https://github.com/QUB3X/Appunti/blob/6b4a7ee39cc99a015f36ec93ff03fc593ba68e95/API/Algoritmi.tex#L436

**Comment by andreafra** [comment]
Pepega

**Comment by andreafra** [comment]
Ora è corretto (il numero 3 era un refuso 😛 )
